version: '3'


services: 
  # frontend:
  #   container_name: frontend
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile

  backend:
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    environment: 
      - PORT=8080